-- Run in the Supabase SQL Editor if the Result table or its browser policies
-- have not already been configured. The portal uses these exact column names.

create table if not exists public."Result" (
  id bigint generated by default as identity primary key,
  name text not null,
  force_no text not null,
  rank text not null,
  unit text not null,
  score integer not null,
  total integer not null,
  percentage numeric not null,
  feedback text,
  completion_time timestamptz not null,
  created_at timestamptz not null default now()
);

alter table public."Result" enable row level security;

create policy "Public trainees can insert results"
on public."Result" for insert to anon
with check (true);

create policy "Public trainees can view results"
on public."Result" for select to anon
using (true);

create policy "Public trainees can update feedback"
on public."Result" for update to anon
using (true)
with check (true);
